### ISSUE TITLE
IT Holidays and sub-region

### ISSUE THREAD

**Issue by ste26054** [holidays/definitions#127]
Hello,

It appears that the holiday "Feast of Saints Peter and Paul" Holiday, taking place on the 29th June, is also taking place in Rome (https://en.wikipedia.org/wiki/Feast_of_Saints_Peter_and_Paul and https://www.officeholidays.com/countries/global/st_peter_and_paul.php).

Hence, can we create a sub-region for `it` such as `it_rome`? Because for Italy it is observed only in this city, we cannot use a full ISO-3166-2 code.

I am okay to do a pull request

**Comment by ppeble** [comment]
Hm, this is a good question! To make sure I understand correctly: you are saying that we cannot use `IT_RM` because that code represents more than just the city of Rome?

I ask because according to the [list of provinces in Italy from Wikipedia](https://en.wikipedia.org/wiki/Provinces_of_Italy#List_of_provinces) I see 'Rome' as a province and coded as a 'Metropolitan City'. I also found `IT_RM` on the official [ISO site for IT](https://www.iso.org/obp/ui/#iso:code:3166:IT). Is there a different between the 'province' of Rome and the city itself? 🤔

**Comment by ste26054** [comment]
You are right actually, when I read the [ISO 3166-2:IT](https://en.wikipedia.org/wiki/ISO_3166-2:IT) wiki page I missread and thought that `IT_RM` represented the Lazio region itself rather than it being a part of this region.

Now it actually makes sense to just use `IT_RM` iso code!

**Comment by ppeble** [comment]
Great! 🎉 

If it's alright with you I'll leave this issue open while you work on the PR. Please reference it when you open the PR and feel free to tag me for a review. Thanks again!

**Comment by ttwo32** [comment]
Thank you !! :)

**Comment by ste26054** [comment]
@ppeble PR done!

**Comment by ttwo32** [comment]
Great  !!

**Comment by ppeble** [comment]
PR merged! Thanks again!
