### ISSUE TITLE
Question about the next release

### ISSUE THREAD

**Issue by kilimandzsaro** [holidays/definitions#56]
Hi, I just want to ask when do you plan the next release?

**Comment by ttwo32** [comment]
Hi @kilimandzsaro.
I'm sorry for the delay.
I plan the next release at this weekend.
Could you wait until this weekend?
Thanks.

**Comment by ppeble** [comment]
I apologize for my tardiness around merges and releases. Having a 6 month old is _killing_ my free time. 😦 

I will do a release either today or tomorrow that will include all of the recent updates. Thanks for your patience!

**Comment by spaceneedle2019** [comment]
> Having a 6 month old is _killing_ my free time.

No problem. Keep going! And welcome to family life. :)

**Comment by spaceneedle2019** [comment]
@ppeble 

> Having a 6 month old is _killing_ my free time.

No problem. Keep going! And welcome to family life. :)

**Comment by kilimandzsaro** [comment]
No problem at all, I just wanted to know when can I count on it :) @ppeble have fun with your new family member.

**Comment by ppeble** [comment]
I'm awful, sorry. But I am at a conference this week (gophercon!) so I will have free time between talks and in the evenings and so I promise a release will go out before Friday. Thank you again for being so nice and understanding and thank you to @ttwo32 for carrying the load while I adjust to my new life schedule.

**Comment by ppeble** [comment]
Okay! FINALLY FINALLY FINALLY


FINALLY

https://github.com/holidays/holidays/pull/281

It's everything that has been done in since v5.6.0. That PR is just a formality, once everything passes and @ttwo32 gives it a once-over I'll merge, build, and then publish the gem.

**Comment by ppeble** [comment]
Thank you again. v5.7.0 is out on rubygems.org with the latest definitions. Please let me know if anything looks amiss.

**Comment by spaceneedle2019** [comment]
Thank you. Very cool, so I can finally remove the temporary custom calendars from our application. I'll try it upcoming week. :)

**Comment by ppeble** [comment]
Yes! And thanks again. Everyone has been so nice to me, even though I constantly blew past the commitments that I said for myself. Thank you thank you thank you. ❤️

**Comment by ppeble** [comment]
Oh and @spaceneedle2019, since you've updated so many definitions, this will probably affect you more than most. Please note the changes in this PR: https://github.com/holidays/definitions/pull/26

Here is the issue where I lay out the details of what I did: https://github.com/holidays/definitions/issues/7

Long story short, I want to switch how the tests are written, away from pure ruby. I'm not going to accept any more PRs until I merge the linked one since trying to keep it up to date has been a nightmare. I'm about 97% done with the changes required to the ruby side to make this all work and in the end it should work identically. Only how we generate tests changes. But I want you to be aware so that you don't spend a lot of time updating tests in ruby and then have to switch the format. If you want to talk more about the specifics you can hit me up on twitter (https://twitter.com/philpeble) or we can talk on slack or email or whatever. Just let me know!

**Comment by spaceneedle2019** [comment]
You're very welcome, @ppeble. 😃

I already noticed that you guys want to change the way to writing tests for the definitions. Sounds like a good thing, there is no doubt about it. I'll keep an eye on it and remain in the background for now. :)

P.S.: Some moments ago I've added you on Twitter. 🙂
