### ISSUE TITLE
Discuss JP holidays: The Emperor's Birthday change from 2019

### ISSUE THREAD

**Issue by anhnt2808** [holidays/definitions#91]
I found that Japan's Emperor will change in 2019. So the old Emperor's Birthday ( 23/12 ) will be not a holiday from 2019. And new imperial era will start at 1/5, but the new Emperor's Birthday is 23/2, so 2019 will have not the Emperor's Birthday holiday. The new Emperor's Birthday ( 23/2) is a holiday from 2020. 
I think that have to update 'jp.yml' for it. And I'm not sure that it have any other changes on holidays or not.

**Comment by ttwo32** [comment]
Hello @anhnt2808 !!
Thank you for your report!!
I know that there is no Emperor's Birthday, holiday of 2019 in Japan. Because I'm Japanese.:)
In 2019, Japanese government considers adding new holidays May 1st instead of the Emperor's Birthday, but they have to change the holidays law.
I did not intend to change until the government announced, but it is a fact that there is no emperor's birthday in 2019, let's change 'jp.yml' first. :)
I will change it at this weekend. But other pull requests are waiting for merging, Would you wait for my next instruction?

**Comment by anhnt2808** [comment]
Hi @ttwo32 
Thank you for your answer.
Yes, I'm waiting. I think it will be fine until the end of 2018.
Thank you again for your support.
P/s: I'm working in Japan. That's why I face this problem. :)

**Comment by ttwo32** [comment]
@anhnt2808 
Sorry, lazy response.
> Should I close this issue, or just leave it here?
Just leave it. 
After release, i will close this issue.:)

> P/s: I'm working in Japan. That's why I face this problem. :)
Wow!! I'm glad to hear that. :)
I wonder that this gem is used in Japan.

**Comment by ttwo32** [comment]
@anhnt2808 
I have pushed a commit.
This commit will be merged with other pull request https://github.com/holidays/holidays/pull/308 .
But Owner's review is required. Could you wait until merged?

Hi @ppeble !!
Please review [my Pull Request](https://github.com/holidays/holidays/pull/308) at your free time :)

**Comment by anhnt2808** [comment]
@ttwo32 
Sorry for the late reply.
Yes, I can wait.
Thank you for support.

**Comment by ppeble** [comment]
I think that this is resolved now that I have merged https://github.com/holidays/holidays/pull/315. Sorry for the delay! 🙇
